const LEAD_JOURNEYS = Object.freeze([
  'contact',
  'support',
  'consumer_order',
  'content_download',
  'epigenetics_inquiry',
])

const LEAD_STATUSES = Object.freeze({
  RECEIVED: 'RECEIVED',
  PERSISTED: 'PERSISTED',
  PENDING_HANDOFF: 'PENDING_HANDOFF',
  PROCESSING: 'PROCESSING',
  DELIVERED: 'DELIVERED',
  RETRY_PENDING: 'RETRY_PENDING',
  FAILED_TERMINAL: 'FAILED_TERMINAL',
})

const OUTBOX_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  RETRY_PENDING: 'RETRY_PENDING',
  DELIVERED: 'DELIVERED',
  FAILED_TERMINAL: 'FAILED_TERMINAL',
})

const DELIVERY_RESULTS = Object.freeze({
  DELIVERED: 'DELIVERED',
  RETRYABLE_ERROR: 'RETRYABLE_ERROR',
  TERMINAL_ERROR: 'TERMINAL_ERROR',
  NO_PROVIDER_CONFIGURED: 'NO_PROVIDER_CONFIGURED',
})

const DELIVERY_CHANNELS = Object.freeze({
  CRM: 'CRM',
  MAIL: 'MAIL',
})

module.exports = {
  LEAD_JOURNEYS,
  LEAD_STATUSES,
  OUTBOX_STATUSES,
  DELIVERY_RESULTS,
  DELIVERY_CHANNELS,
}
