# Dockerfile.dev

FROM node:22-alpine
WORKDIR /app

# Installiert Abhängigkeiten (wird dank Caching schnell sein)
COPY package*.json ./
RUN npm ci

# Definiert den Port des Development Servers (Oft 3000, 5173 oder 8080)
EXPOSE 3000

# Startet den Development Server (wichtig: muss im Vordergrund bleiben)
CMD ["npm", "run", "dev"]