import json
import os

languages = ['cs', 'da', 'en', 'es', 'fr', 'it', 'nl', 'pl', 'pt']

translations = {
    "en": {
        "hero": {
            "caption": "Point-of-care Performance",
            "title": "IglooPro:\nPoint-of-Care. Perfect. Immediate.",
            "description": "Secure the performance package: Your IglooPro is ready for use in 48 hours – guaranteed.",
            "cta": "Book 15-Minute Performance Analysis Now",
            "cta_downloads": "Download Info Materials",
            "stat1": {"value": "48h", "label": "Ready for use after order"},
            "stat2": {"value": "CV < 2%", "label": "Precision across the entire measurement range"}
        },
        "about": {
            "caption": "YOUR PERFORMANCE GUARANTOR",
            "title": "Excellence and Safety: The Standard We Set.",
            "text1": "The IglooPro is a premium device. But true premium performance only comes from perfect, risk-free commissioning. A standard delivery leaves the complexity to you. We take responsibility for the result.",
            "text2": "That is why we exclusively deliver the 48-hour setup promise. Our performance pillars guarantee that your POC workflow is optimized from the very first second and that you can use diagnostic excellence immediately.",
            "cta": "Secure Exclusive Benefit"
        },
        "doctors": {
            "caption": "DIAGNOSTICS FOCUS",
            "title": "Precise Diagnostics. Immediate Results at the Point-of-Care.",
            "description": "Discover with systems like the Igloo Pro from DX365 how you can optimize your patient care and provide important diagnoses directly at the point of treatment – with lab-accurate results in minutes.",
            "cta": "To the Igloo Pro System"
        },
        "services": {
            "caption": "DIAGNOSTICS FOCUS",
            "title": "Key Areas of Preventive Diagnostics",
            "poc_systemloesungen": {"title": "POC System Solutions", "description": "Your control center for diagnostics. Mobile analyzers that deliver lab-accurate results in minutes directly at the point of treatment (e.g. Igloo Pro)."},
            "praeventions_checks": {"title": "Preventive Health Checks", "description": "Prevention reimagined. Rapid determination of important biomarkers (e.g. Vitamin D, CRP, HbA1c) for early risk detection and individual health advice."},
            "infektion_entzuendung": {"title": "Infection & Inflammation Markers", "description": "Quick answers in critical cases. Immediate analysis of inflammation values (CRP, PCT, IL-6) and infectious diseases – essential for acute care and triage."},
            "stoffwechsel_herz": {"title": "Metabolism & Heart Health", "description": "Important indicators at a glance. Precise measurement of HbA1c, cholesterol profiles and cardiac markers (e.g. D-Dimer) for monitoring chronic diseases."},
            "hormon_tests": {"title": "Hormone & Endocrinology Tests", "description": "Special diagnostics made easy. Wide range of tests for thyroid and reproduction hormones (TSH, AMH) for specialized practices and pharmacies."},
            "kompatibilitaet_integration": {"title": "Cross-Manufacturer Compatibility", "description": "Maximum flexibility. Thanks to universal technology, our devices evaluate 90% of all lateral flow tests on the market. Investment security through openness."}
        },
        "testimonials": {
            "caption": "TESTIMONIALS",
            "title": "What Our Users Say About the Igloo Pro System",
            "ratingLabel": "Overall Rating\nbased on 3500+ reviews",
            "positiveLabel": "Positive Rating",
            "richard_pollock": {"role": "Dentist (Real Review)", "title": "Biological Dentist and Implant Surgeon / Chelsea Dental Clinic", "focus": "Fast On-Site Health Checks (Prevention, Vitamin D)", "text": "Carrying out analysis of Vitamin D levels and other key health indicators on-site cannot be underestimated. The Igloo Pro enables me to perform a simple capillary blood test, to ascertain patients’ needs and to then guide them as to which additional supplements they might require to optimise treatment. This capability is proving transformative in terms of patient outcomes."},
            "eva_schmidt": {"role": "Pharmacy", "title": "Owner / Löwen-Apotheke, Berlin", "focus": "The Next Step in Prevention Consulting (Customer Loyalty, Speed)", "text": "Since we started using the Igloo Pro System, our role as health consultants has been extremely strengthened. Customers greatly appreciate being able to determine important values like CRP or cholesterol in minutes instead of waiting weeks for appointments. A real win-win situation for customer loyalty and service quality."},
            "martin_fischer": {"role": "General Practitioner/Practice", "title": "Specialist in Internal Medicine / Internal Medicine Practice Dr. Fischer", "focus": "Immediate Diagnostics for Acute Patients (Efficiency, Therapy Decision)", "text": "The ability to determine inflammation markers like CRP immediately in the practice has revolutionized our treatment workflow. We can decide faster whether antibiotic therapy is necessary for patients with unclear infections and prevent unnecessary referrals. This saves us time and significantly increases patient satisfaction."},
            "julia_bergmann": {"role": "Clinic/Lab", "title": "Head of Laboratory & Diagnostics / Klinikum Nord", "focus": "System Compatibility & Reliability (Flexibility, Bundling)", "text": "The Igloo Pro is the most flexible Point-of-Care device we have ever evaluated. The cross-manufacturer compatibility for lateral flow tests is a huge advantage that allows us to standardize our POC devices and save costs without having to forego the proven reliability of the results."}
        },
        "blog": {
            "caption": "Blog & News",
            "title": "Our Articles About Health"
        }
    },
    "fr": {
        "hero": {
            "caption": "Performance au point de service",
            "title": "IglooPro:\nPoint-of-Care. Parfait. Immédiat.",
            "description": "Assurez-vous le pack performance : Votre IglooPro est prêt à l'emploi en 48 heures – garanti.",
            "cta": "Réserver une analyse de performance de 15 minutes maintenant",
            "cta_downloads": "Télécharger les documents d'information",
            "stat1": {"value": "48h", "label": "Prêt à l'emploi après commande"},
            "stat2": {"value": "CV < 2%", "label": "Précision sur toute la plage de mesure"}
        },
        "about": {
            "caption": "VOTRE GARANT DE PERFORMANCE",
            "title": "Excellence et Sécurité : La norme que nous fixons.",
            "text1": "L'IglooPro est un appareil haut de gamme. Mais la véritable performance haut de gamme ne vient que d'une mise en service parfaite et sans risque. Une livraison standard vous laisse la complexité. Nous prenons la responsabilité du résultat.",
            "text2": "C'est pourquoi nous livrons exclusivement la promesse de configuration en 48 heures. Nos piliers de performance garantissent que votre flux de travail POC est optimisé dès la première seconde et que vous pouvez utiliser l'excellence diagnostique immédiatement.",
            "cta": "Garantir un avantage exclusif"
        },
        "doctors": {
            "caption": "FOCUS DIAGNOSTIC",
            "title": "Diagnostic précis. Résultats immédiats au Point-of-Care.",
            "description": "Découvrez avec des systèmes comme l'Igloo Pro de DX365 comment optimiser vos soins aux patients et fournir des diagnostics importants directement sur le lieu de traitement – avec des résultats précis en quelques minutes.",
            "cta": "Vers le système Igloo Pro"
        },
        "services": {
            "caption": "FOCUS DIAGNOSTIC",
            "title": "Domaines clés du diagnostic préventif",
            "poc_systemloesungen": {"title": "Solutions système POC", "description": "Votre centre de contrôle pour le diagnostic. Analyseurs mobiles qui fournissent des résultats de laboratoire en quelques minutes directement sur le lieu de traitement (par ex. Igloo Pro)."},
            "praeventions_checks": {"title": "Bilans de santé préventifs", "description": "La prévention repensée. Détermination rapide de biomarqueurs importants (par ex. Vitamine D, CRP, HbA1c) pour la détection précoce des risques et des conseils de santé individuels."},
            "infektion_entzuendung": {"title": "Marqueurs d'infection et d'inflammation", "description": "Réponses rapides dans les cas critiques. Analyse immédiate des valeurs d'inflammation (CRP, PCT, IL-6) et des maladies infectieuses – essentiel pour les soins aigus et le triage."},
            "stoffwechsel_herz": {"title": "Métabolisme et santé cardiaque", "description": "Indicateurs importants en un coup d'œil. Mesure précise de l'HbA1c, des profils de cholestérol et des marqueurs cardiaques (par ex. D-Dimère) pour la surveillance des maladies chroniques."},
            "hormon_tests": {"title": "Tests hormonaux et endocrinologie", "description": "Le diagnostic spécialisé rendu facile. Large gamme de tests pour les hormones thyroïdiennes et de reproduction (TSH, AMH) pour les cabinets spécialisés et les pharmacies."},
            "kompatibilitaet_integration": {"title": "Compatibilité multi-fabricants", "description": "Flexibilité maximale. Grâce à la technologie universelle, nos appareils évaluent 90% de tous les tests à flux latéral sur le marché. Sécurité d'investissement grâce à l'ouverture."}
        },
        "testimonials": {
            "caption": "TÉMOIGNAGES",
            "title": "Ce que disent nos utilisateurs à propos du système Igloo Pro",
            "ratingLabel": "Note globale\nbasée sur 3500+ avis",
            "positiveLabel": "Avis positif",
            "richard_pollock": {"role": "Dentiste (Avis réel)", "title": "Dentiste biologique et chirurgien implantaire / Chelsea Dental Clinic", "focus": "Bilans de santé rapides sur site (Prévention, Vitamine D)", "text": "L'analyse des niveaux de vitamine D et d'autres indicateurs de santé clés sur site ne peut être sous-estimée. L'Igloo Pro me permet d'effectuer un simple test sanguin capillaire, de vérifier les besoins des patients et de les guider ensuite vers les suppléments supplémentaires dont ils pourraient avoir besoin pour optimiser le traitement. Cette capacité s'avère transformatrice en termes de résultats pour les patients."},
            "eva_schmidt": {"role": "Pharmacie", "title": "Propriétaire / Löwen-Apotheke, Berlin", "focus": "La prochaine étape du conseil en prévention (Fidélisation client, Rapidité)", "text": "Depuis que nous utilisons le système Igloo Pro, notre rôle de conseillers en santé s'est considérablement renforcé. Les clients apprécient énormément de pouvoir déterminer des valeurs importantes comme la CRP ou le cholestérol en quelques minutes au lieu d'attendre des semaines pour des rendez-vous. Une véritable situation gagnant-gagnant pour la fidélisation des clients et la qualité du service."},
            "martin_fischer": {"role": "Médecin généraliste/Cabinet", "title": "Spécialiste en médecine interne / Cabinet de médecine interne Dr. Fischer", "focus": "Diagnostic immédiat pour les patients aigus (Efficacité, Décision thérapeutique)", "text": "La possibilité de déterminer immédiatement des marqueurs d'inflammation comme la CRP au cabinet a révolutionné notre flux de traitement. Nous pouvons décider plus rapidement si une antibiothérapie est nécessaire pour les patients souffrant d'infections peu claires et éviter les renvois inutiles. Cela nous fait gagner du temps et augmente considérablement la satisfaction des patients."},
            "julia_bergmann": {"role": "Clinique/Laboratoire", "title": "Chef de laboratoire et diagnostic / Klinikum Nord", "focus": "Compatibilité et fiabilité du système (Flexibilité, Regroupement)", "text": "L'Igloo Pro est l'appareil Point-of-Care le plus flexible que nous ayons jamais évalué. La compatibilité multi-fabricants pour les tests à flux latéral est un énorme avantage qui nous permet de standardiser nos appareils POC et d'économiser des coûts sans avoir à renoncer à la fiabilité éprouvée des résultats."}
        },
        "blog": {
            "caption": "Blog et actualités",
            "title": "Nos articles sur la santé"
        }
    },
    "es": {
        "hero": {
            "caption": "Rendimiento en el punto de atención",
            "title": "IglooPro:\nPoint-of-Care. Perfecto. Inmediato.",
            "description": "Asegure el paquete de rendimiento: Su IglooPro está listo para usar en 48 horas, garantizado.",
            "cta": "Reservar análisis de rendimiento de 15 minutos ahora",
            "cta_downloads": "Descargar materiales informativos",
            "stat1": {"value": "48h", "label": "Listo para usar después del pedido"},
            "stat2": {"value": "CV < 2%", "label": "Precisión en todo el rango de medición"}
        },
        "about": {
            "caption": "SU GARANTÍA DE RENDIMIENTO",
            "title": "Excelencia y Seguridad: El estándar que establecemos.",
            "text1": "El IglooPro es un dispositivo premium. Pero el verdadero rendimiento premium solo proviene de una puesta en marcha perfecta y sin riesgos. Una entrega estándar le deja la complejidad a usted. Nosotros asumimos la responsabilidad del resultado.",
            "text2": "Por eso entregamos exclusivamente la promesa de configuración en 48 horas. Nuestros pilares de rendimiento garantizan que su flujo de trabajo POC esté optimizado desde el primer segundo y que pueda utilizar la excelencia diagnóstica de inmediato.",
            "cta": "Asegurar beneficio exclusivo"
        },
        "doctors": {
            "caption": "ENFOQUE DIAGNÓSTICO",
            "title": "Diagnóstico preciso. Resultados inmediatos en el Point-of-Care.",
            "description": "Descubra con sistemas como el Igloo Pro de DX365 cómo puede optimizar la atención al paciente y proporcionar diagnósticos importantes directamente en el lugar del tratamiento, con resultados de laboratorio en minutos.",
            "cta": "Al sistema Igloo Pro"
        },
        "services": {
            "caption": "ENFOQUE DIAGNÓSTICO",
            "title": "Áreas clave del diagnóstico preventivo",
            "poc_systemloesungen": {"title": "Soluciones de sistema POC", "description": "Su centro de control para el diagnóstico. Analizadores móviles que ofrecen resultados de laboratorio en minutos directamente en el lugar del tratamiento (p. ej., Igloo Pro)."},
            "praeventions_checks": {"title": "Chequeos preventivos de salud", "description": "La prevención reinventada. Determinación rápida de biomarcadores importantes (p. ej., Vitamina D, CRP, HbA1c) para la detección temprana de riesgos y asesoramiento de salud individual."},
            "infektion_entzuendung": {"title": "Marcadores de infección e inflamación", "description": "Respuestas rápidas en casos críticos. Análisis inmediato de valores de inflamación (CRP, PCT, IL-6) y enfermedades infecciosas, esencial para cuidados agudos y triaje."},
            "stoffwechsel_herz": {"title": "Metabolismo y salud cardíaca", "description": "Indicadores importantes de un vistazo. Medición precisa de HbA1c, perfiles de colesterol y marcadores cardíacos (p. ej., Dímero D) para el monitoreo de enfermedades crónicas."},
            "hormon_tests": {"title": "Pruebas hormonales y endocrinología", "description": "Diagnóstico especializado simplificado. Amplia gama de pruebas para hormonas tiroideas y reproductivas (TSH, AMH) para prácticas especializadas y farmacias."},
            "kompatibilitaet_integration": {"title": "Compatibilidad entre fabricantes", "description": "Máxima flexibilidad. Gracias a la tecnología universal, nuestros dispositivos evalúan el 90% de todas las pruebas de flujo lateral en el mercado. Seguridad de inversión a través de la apertura."}
        },
        "testimonials": {
            "caption": "TESTIMONIOS",
            "title": "Lo que dicen nuestros usuarios sobre el sistema Igloo Pro",
            "ratingLabel": "Calificación general\nbasada en 3500+ reseñas",
            "positiveLabel": "Calificación positiva",
            "richard_pollock": {"role": "Dentista (Reseña real)", "title": "Dentista biológico y cirujano de implantes / Chelsea Dental Clinic", "focus": "Chequeos de salud rápidos en el lugar (Prevención, Vitamina D)", "text": "Realizar análisis de niveles de Vitamina D y otros indicadores clave de salud en el lugar no puede subestimarse. El Igloo Pro me permite realizar una simple prueba de sangre capilar, determinar las necesidades de los pacientes y luego guiarlos sobre qué suplementos adicionales podrían necesitar para optimizar el tratamiento. Esta capacidad está demostrando ser transformadora en términos de resultados para los pacientes."},
            "eva_schmidt": {"role": "Farmacia", "title": "Propietaria / Löwen-Apotheke, Berlín", "focus": "El siguiente paso en consultoría de prevención (Lealtad del cliente, Velocidad)", "text": "Desde que comenzamos a usar el sistema Igloo Pro, nuestro papel como consultores de salud se ha fortalecido enormemente. Los clientes aprecian mucho poder determinar valores importantes como CRP o colesterol en minutos en lugar de esperar semanas para citas. Una verdadera situación de ganar-ganar para la lealtad del cliente y la calidad del servicio."},
            "martin_fischer": {"role": "Médico general/Consulta", "title": "Especialista en Medicina Interna / Consulta de Medicina Interna Dr. Fischer", "focus": "Diagnóstico inmediato para pacientes agudos (Eficiencia, Decisión terapéutica)", "text": "La capacidad de determinar marcadores de inflamación como CRP inmediatamente en la consulta ha revolucionado nuestro flujo de trabajo de tratamiento. Podemos decidir más rápido si es necesaria una terapia antibiótica para pacientes con infecciones poco claras y prevenir derivaciones innecesarias. Esto nos ahorra tiempo y aumenta significativamente la satisfacción del paciente."},
            "julia_bergmann": {"role": "Clínica/Laboratorio", "title": "Jefa de Laboratorio y Diagnóstico / Klinikum Nord", "focus": "Compatibilidad y fiabilidad del sistema (Flexibilidad, Agrupación)", "text": "El Igloo Pro es el dispositivo Point-of-Care más flexible que jamás hayamos evaluado. La compatibilidad entre fabricantes para pruebas de flujo lateral es una gran ventaja que nos permite estandarizar nuestros dispositivos POC y ahorrar costos sin tener que renunciar a la fiabilidad probada de los resultados."}
        },
        "blog": {
            "caption": "Blog y noticias",
            "title": "Nuestros artículos sobre salud"
        }
    },
    "it": {
        "hero": {"caption": "Prestazioni Point-of-Care", "title": "IglooPro:\nPoint-of-Care. Perfetto. Immediato.", "description": "Assicurati il pacchetto prestazioni: Il tuo IglooPro è pronto all'uso in 48 ore – garantito.", "cta": "Prenota ora l'analisi delle prestazioni di 15 minuti", "cta_downloads": "Scarica materiale informativo", "stat1": {"value": "48h", "label": "Pronto all'uso dopo l'ordine"}, "stat2": {"value": "CV < 2%", "label": "Precisione sull'intero intervallo di misurazione"}},
        "about": {"caption": "IL TUO GARANTE DI PRESTAZIONI", "title": "Eccellenza e Sicurezza: Lo standard che impostiamo.", "text1": "L'IglooPro è un dispositivo premium. Ma le vere prestazioni premium derivano solo da una messa in servizio perfetta e priva di rischi. Una consegna standard ti lascia la complessità. Noi ci assumiamo la responsabilità del risultato.", "text2": "Ecco perché forniamo esclusivamente la promessa di configurazione in 48 ore. I nostri pilastri delle prestazioni garantiscono che il tuo flusso di lavoro POC sia ottimizzato fin dal primo secondo e che tu possa utilizzare immediatamente l'eccellenza diagnostica.", "cta": "Assicura un vantaggio esclusivo"},
        "doctors": {"caption": "FOCUS DIAGNOSTICA", "title": "Diagnostica precisa. Risultati immediati al Point-of-Care.", "description": "Scopri con sistemi come l'Igloo Pro di DX365 come ottimizzare la cura del paziente e fornire diagnosi importanti direttamente nel luogo del trattamento – con risultati di laboratorio in pochi minuti.", "cta": "Al sistema Igloo Pro"},
        "services": {"caption": "FOCUS DIAGNOSTICA", "title": "Aree chiave della diagnostica preventiva", "poc_systemloesungen": {"title": "Soluzioni di sistema POC", "description": "Il tuo centro di controllo per la diagnostica. Analizzatori mobili che forniscono risultati di laboratorio in pochi minuti direttamente nel luogo del trattamento (es. Igloo Pro)."}, "praeventions_checks": {"title": "Controlli sanitari preventivi", "description": "Prevenzione ripensata. Determinazione rapida di importanti biomarcatori (es. Vitamina D, CRP, HbA1c) per il rilevamento precoce dei rischi e consulenza sanitaria individuale."}, "infektion_entzuendung": {"title": "Marcatori di infezione e infiammazione", "description": "Risposte rapide nei casi critici. Analisi immediata dei valori di infiammazione (CRP, PCT, IL-6) e malattie infettive – essenziale per le cure acute e il triage."}, "stoffwechsel_herz": {"title": "Metabolismo e salute cardiaca", "description": "Indicatori importanti a colpo d'occhio. Misurazione precisa di HbA1c, profili di colesterolo e marcatori cardiaci (es. D-Dimero) per il monitoraggio delle malattie croniche."}, "hormon_tests": {"title": "Test ormonali ed endocrinologia", "description": "Diagnostica specializzata resa facile. Ampia gamma di test per ormoni tiroidei e riproduttivi (TSH, AMH) per studi specializzati e farmacie."}, "kompatibilitaet_integration": {"title": "Compatibilità multi-produttore", "description": "Massima flessibilità. Grazie alla tecnologia universale, i nostri dispositivi valutano il 90% di tutti i test a flusso laterale sul mercato. Sicurezza dell'investimento attraverso l'apertura."}},
        "testimonials": {"caption": "TESTIMONIANZE", "title": "Cosa dicono i nostri utenti sul sistema Igloo Pro", "ratingLabel": "Valutazione complessiva\nbasata su 3500+ recensioni", "positiveLabel": "Valutazione positiva", "richard_pollock": {"role": "Dentista (Recensione reale)", "title": "Dentista biologico e chirurgo implantare / Chelsea Dental Clinic", "focus": "Controlli sanitari rapidi in loco (Prevenzione, Vitamina D)", "text": "L'esecuzione dell'analisi dei livelli di Vitamina D e di altri indicatori sanitari chiave in loco non può essere sottovalutata. L'Igloo Pro mi consente di eseguire un semplice esame del sangue capillare, accertare le esigenze dei pazienti e guidarli su quali integratori aggiuntivi potrebbero richiedere per ottimizzare il trattamento. Questa capacità si sta rivelando trasformativa in termini di risultati per i pazienti."}, "eva_schmidt": {"role": "Farmacia", "title": "Proprietaria / Löwen-Apotheke, Berlino", "focus": "Il prossimo passo nella consulenza di prevenzione (Fidelizzazione cliente, Velocità)", "text": "Da quando abbiamo iniziato a utilizzare il sistema Igloo Pro, il nostro ruolo di consulenti sanitari si è notevolmente rafforzato. I clienti apprezzano molto la possibilità di determinare valori importanti come CRP o colesterolo in pochi minuti invece di aspettare settimane per gli appuntamenti. Una vera situazione vantaggiosa per la fidelizzazione dei clienti e la qualità del servizio."}, "martin_fischer": {"role": "Medico di base/Studio", "title": "Specialista in Medicina Interna / Studio di Medicina Interna Dr. Fischer", "focus": "Diagnostica immediata per pazienti acuti (Efficienza, Decisione terapeutica)", "text": "La capacità di determinare immediatamente marcatori di infiammazione come la CRP nello studio ha rivoluzionato il nostro flusso di lavoro terapeutico. Possiamo decidere più rapidamente se è necessaria una terapia antibiotica per pazienti con infezioni non chiare e prevenire rinvii non necessari. Questo ci fa risparmiare tempo e aumenta significativamente la soddisfazione del paziente."}, "julia_bergmann": {"role": "Clinica/Laboratorio", "title": "Responsabile Laboratorio e Diagnostica / Klinikum Nord", "focus": "Compatibilità e affidabilità del sistema (Flessibilità, Raggruppamento)", "text": "L'Igloo Pro è il dispositivo Point-of-Care più flessibile che abbiamo mai valutato. La compatibilità multi-produttore per i test a flusso laterale è un enorme vantaggio che ci consente di standardizzare i nostri dispositivi POC e risparmiare sui costi senza dover rinunciare alla comprovata affidabilità dei risultati."}},
        "blog": {"caption": "Blog e notizie", "title": "I nostri articoli sulla salute"}
    },
    "pl": {
        "hero": {"caption": "Wydajność w miejscu opieki", "title": "IglooPro:\nPoint-of-Care. Perfekcyjny. Natychmiastowy.", "description": "Zapewnij sobie pakiet wydajności: Twój IglooPro jest gotowy do użycia w 48 godzin – gwarantowane.", "cta": "Zarezerwuj 15-minutową analizę wydajności teraz", "cta_downloads": "Pobierz materiały informacyjne", "stat1": {"value": "48h", "label": "Gotowy do użycia po zamówieniu"}, "stat2": {"value": "CV < 2%", "label": "Precyzja w całym zakresie pomiarowym"}},
        "about": {"caption": "TWOJA GWARANCJA WYDAJNOŚCI", "title": "Doskonałość i Bezpieczeństwo: Standard, który wyznaczamy.", "text1": "IglooPro to urządzenie premium. Ale prawdziwa wydajność premium pochodzi tylko z perfekcyjnego, wolnego od ryzyka uruchomienia. Standardowa dostawa pozostawia złożoność Tobie. My bierzemy odpowiedzialność za wynik.", "text2": "Dlatego dostarczamy wyłącznie obietnicę konfiguracji w 48 godzin. Nasze filary wydajności gwarantują, że Twój przepływ pracy POC jest zoptymalizowany od pierwszej sekundy i że możesz natychmiast korzystać z doskonałości diagnostycznej.", "cta": "Zapewnij ekskluzywną korzyść"},
        "doctors": {"caption": "FOKUS NA DIAGNOSTYKĘ", "title": "Precyzyjna diagnostyka. Natychmiastowe wyniki w Point-of-Care.", "description": "Odkryj z systemami takimi jak Igloo Pro od DX365, jak możesz zoptymalizować opiekę nad pacjentem i dostarczać ważne diagnozy bezpośrednio w miejscu leczenia – z wynikami laboratoryjnymi w kilka minut.", "cta": "Do systemu Igloo Pro"},
        "services": {"caption": "FOKUS NA DIAGNOSTYKĘ", "title": "Kluczowe obszary diagnostyki profilaktycznej", "poc_systemloesungen": {"title": "Rozwiązania systemowe POC", "description": "Twoje centrum sterowania diagnostyką. Mobilne analizatory dostarczające wyniki laboratoryjne w kilka minut bezpośrednio w miejscu leczenia (np. Igloo Pro)."}, "praeventions_checks": {"title": "Profilaktyczne badania zdrowotne", "description": "Profilaktyka wymyślona na nowo. Szybkie określanie ważnych biomarkerów (np. Witamina D, CRP, HbA1c) w celu wczesnego wykrywania ryzyka i indywidualnego poradnictwa zdrowotnego."}, "infektion_entzuendung": {"title": "Markery infekcji i stanów zapalnych", "description": "Szybkie odpowiedzi w krytycznych przypadkach. Natychmiastowa analiza wartości zapalnych (CRP, PCT, IL-6) i chorób zakaźnych – niezbędna w ostrej opiece i segregacji."}, "stoffwechsel_herz": {"title": "Metabolizm i zdrowie serca", "description": "Ważne wskaźniki na pierwszy rzut oka. Precyzyjny pomiar HbA1c, profili cholesterolu i markerów sercowych (np. D-Dimer) do monitorowania chorób przewlekłych."}, "hormon_tests": {"title": "Testy hormonalne i endokrynologia", "description": "Specjalistyczna diagnostyka stała się prosta. Szeroka gama testów hormonów tarczycy i rozrodczych (TSH, AMH) dla specjalistycznych praktyk i aptek."}, "kompatibilitaet_integration": {"title": "Kompatybilność między producentami", "description": "Maksymalna elastyczność. Dzięki uniwersalnej technologii nasze urządzenia oceniają 90% wszystkich testów przepływu bocznego na rynku. Bezpieczeństwo inwestycji dzięki otwartości."}},
        "testimonials": {"caption": "OPINIE", "title": "Co nasi użytkownicy mówią o systemie Igloo Pro", "ratingLabel": "Ogólna ocena\nna podstawie 3500+ recenzji", "positiveLabel": "Pozytywna ocena", "richard_pollock": {"role": "Dentysta (Prawdziwa recenzja)", "title": "Stomatolog biologiczny i chirurg implantolog / Chelsea Dental Clinic", "focus": "Szybkie kontrole zdrowia na miejscu (Profilaktyka, Witamina D)", "text": "Przeprowadzanie analizy poziomu Witaminy D i innych kluczowych wskaźników zdrowotnych na miejscu nie może być niedoceniane. Igloo Pro pozwala mi wykonać proste badanie krwi włośniczkowej, ustalić potrzeby pacjentów, a następnie wskazać im, jakie dodatkowe suplementy mogą być potrzebne do optymalizacji leczenia. Ta możliwość okazuje się przełomowa w zakresie wyników pacjentów."}, "eva_schmidt": {"role": "Apteka", "title": "Właścicielka / Löwen-Apotheke, Berlin", "focus": "Kolejny krok w doradztwie profilaktycznym (Lojalność klientów, Szybkość)", "text": "Odkąd zaczęliśmy używać systemu Igloo Pro, nasza rola jako doradców zdrowotnych znacznie się wzmocniła. Klienci bardzo cenią możliwość określenia ważnych wartości, takich jak CRP czy cholesterol, w kilka minut zamiast czekać tygodniami na wizyty. Prawdziwa sytuacja win-win dla lojalności klientów i jakości usług."}, "martin_fischer": {"role": "Lekarz ogólny/Praktyka", "title": "Specjalista chorób wewnętrznych / Praktyka Internistyczna Dr Fischer", "focus": "Natychmiastowa diagnostyka dla pacjentów ostrych (Wydajność, Decyzja terapeutyczna)", "text": "Możliwość natychmiastowego określania markerów zapalnych, takich jak CRP, w gabinecie zrewolucjonizowała nasz przepływ pracy. Możemy szybciej zdecydować, czy antybiotykoterapia jest konieczna u pacjentów z niejasnymi infekcjami i zapobiegać niepotrzebnym skierowaniom. To oszczędza nam czas i znacznie zwiększa zadowolenie pacjentów."}, "julia_bergmann": {"role": "Klinika/Laboratorium", "title": "Kierownik Laboratorium i Diagnostyki / Klinikum Nord", "focus": "Kompatybilność i niezawodność systemu (Elastyczność, Łączenie)", "text": "Igloo Pro to najbardziej elastyczne urządzenie Point-of-Care, jakie kiedykolwiek ocenialiśmy. Kompatybilność między producentami testów przepływu bocznego to ogromna zaleta, która pozwala nam standaryzować nasze urządzenia POC i oszczędzać koszty bez konieczności rezygnowania ze sprawdzonej niezawodności wyników."}},
        "blog": {"caption": "Blog i nowości", "title": "Nasze artykuły o zdrowiu"}
    },
    "nl": {
        "hero": {"caption": "Point-of-care Prestaties", "title": "IglooPro:\nPoint-of-Care. Perfect. Onmiddellijk.", "description": "Verzeker het prestatiepakket: Uw IglooPro is binnen 48 uur klaar voor gebruik – gegarandeerd.", "cta": "Boek nu 15-minuten prestatieanalyse", "cta_downloads": "Info-materiaal downloaden", "stat1": {"value": "48u", "label": "Klaar voor gebruik na bestelling"}, "stat2": {"value": "CV < 2%", "label": "Precisie over het hele meetbereik"}},
        "about": {"caption": "UW PRESTATIEGARANT", "title": "Uitmuntendheid en Veiligheid: De standaard die wij stellen.", "text1": "De IglooPro is een premium apparaat. Maar echte premium prestaties komen alleen voort uit een perfecte, risicovrije inbedrijfstelling. Een standaard levering laat de complexiteit aan u over. Wij nemen de verantwoordelijkheid voor het resultaat.", "text2": "Daarom leveren wij exclusief de 48-uurs setup-belofte. Onze prestatiepeilers garanderen dat uw POC-workflow vanaf de eerste seconde is geoptimaliseerd en dat u diagnostische uitmuntendheid onmiddellijk kunt gebruiken.", "cta": "Exclusief voordeel verzekeren"},
        "doctors": {"caption": "DIAGNOSTIEK FOCUS", "title": "Precieze Diagnostiek. Onmiddellijke Resultaten bij Point-of-Care.", "description": "Ontdek met systemen zoals de Igloo Pro van DX365 hoe u uw patiëntenzorg kunt optimaliseren en belangrijke diagnoses direct op de plaats van behandeling kunt stellen – met laboratoriumnauwkeurige resultaten in minuten.", "cta": "Naar het Igloo Pro Systeem"},
        "services": {"caption": "DIAGNOSTIEK FOCUS", "title": "Belangrijkste gebieden van preventieve diagnostiek", "poc_systemloesungen": {"title": "POC-systeemoplossingen", "description": "Uw controlecentrum voor diagnostiek. Mobiele analysers die laboratoriumnauwkeurige resultaten leveren in minuten direct op de plaats van behandeling (bijv. Igloo Pro)."}, "praeventions_checks": {"title": "Preventieve gezondheidschecks", "description": "Preventie opnieuw uitgevonden. Snelle bepaling van belangrijke biomarkers (bijv. Vitamine D, CRP, HbA1c) voor vroege risicodetectie en individueel gezondheidsadvies."}, "infektion_entzuendung": {"title": "Infectie- & Ontstekingsmarkers", "description": "Snelle antwoorden in kritieke gevallen. Onmiddellijke analyse van ontstekingswaarden (CRP, PCT, IL-6) en infectieziekten – essentieel voor acute zorg en triage."}, "stoffwechsel_herz": {"title": "Metabolisme & Hartgezondheid", "description": "Belangrijke indicatoren in één oogopslag. Precieze meting van HbA1c, cholesterolprofielen en cardiale markers (bijv. D-Dimeer) voor het monitoren van chronische ziekten."}, "hormon_tests": {"title": "Hormoon- & Endocrinologie Tests", "description": "Speciale diagnostiek eenvoudig gemaakt. Breed scala aan tests voor schildklier- en reproductiehormonen (TSH, AMH) voor gespecialiseerde praktijken en apotheken."}, "kompatibilitaet_integration": {"title": "Compatibiliteit tussen fabrikanten", "description": "Maximale flexibiliteit. Dankzij universele technologie evalueren onze apparaten 90% van alle laterale flow tests op de markt. Investeringszekerheid door openheid."}},
        "testimonials": {"caption": "GETUIGENISSEN", "title": "Wat onze gebruikers zeggen over het Igloo Pro Systeem", "ratingLabel": "Algemene beoordeling\ngebaseerd op 3500+ beoordelingen", "positiveLabel": "Positieve beoordeling", "richard_pollock": {"role": "Tandarts (Echte recensie)", "title": "Biologische tandarts en implantaatchirurg / Chelsea Dental Clinic", "focus": "Snelle gezondheidschecks ter plaatse (Preventie, Vitamine D)", "text": "Het uitvoeren van analyses van vitamine D-niveaus en andere belangrijke gezondheidsindicatoren ter plaatse mag niet worden onderschat. De Igloo Pro stelt mij in staat om een eenvoudige capillaire bloedtest uit te voeren, de behoeften van patiënten vast te stellen en hen vervolgens te begeleiden naar welke aanvullende supplementen zij mogelijk nodig hebben om de behandeling te optimaliseren. Deze mogelijkheid blijkt transformerend te zijn in termen van patiëntresultaten."}, "eva_schmidt": {"role": "Apotheek", "title": "Eigenaar / Löwen-Apotheke, Berlijn", "focus": "De volgende stap in preventieadvies (Klantloyaliteit, Snelheid)", "text": "Sinds we het Igloo Pro Systeem gebruiken, is onze rol als gezondheidsadviseurs enorm versterkt. Klanten waarderen het enorm om belangrijke waarden zoals CRP of cholesterol in minuten te kunnen bepalen in plaats van weken te wachten op afspraken. Een echte win-win situatie voor klantloyaliteit en servicekwaliteit."}, "martin_fischer": {"role": "Huisarts/Praktijk", "title": "Specialist in Interne Geneeskunde / Interne Geneeskunde Praktijk Dr. Fischer", "focus": "Onmiddellijke diagnostiek voor acute patiënten (Efficiëntie, Therapiebeslissing)", "text": "De mogelijkheid om ontstekingsmarkers zoals CRP onmiddellijk in de praktijk te bepalen, heeft onze behandelingsworkflow revolutionair veranderd. We kunnen sneller beslissen of antibioticatherapie nodig is voor patiënten met onduidelijke infecties en onnodige doorverwijzingen voorkomen. Dit bespaart ons tijd en verhoogt de patiënttevredenheid aanzienlijk."}, "julia_bergmann": {"role": "Kliniek/Laboratorium", "title": "Hoofd Laboratorium & Diagnostiek / Klinikum Nord", "focus": "Systeemcompatibiliteit & Betrouwbaarheid (Flexibiliteit, Bundeling)", "text": "De Igloo Pro is het meest flexibele Point-of-Care apparaat dat we ooit hebben geëvalueerd. De compatibiliteit tussen fabrikanten voor laterale flow tests is een enorm voordeel dat ons in staat stelt onze POC-apparaten te standaardiseren en kosten te besparen zonder in te boeten aan de bewezen betrouwbaarheid van de resultaten."}},
        "blog": {"caption": "Blog & Nieuws", "title": "Onze artikelen over gezondheid"}
    },
    "da": {
        "hero": {"caption": "Point-of-care Ydeevne", "title": "IglooPro:\nPoint-of-Care. Perfekt. Øjeblikkelig.", "description": "Sikr dig præstationspakken: Din IglooPro er klar til brug på 48 timer – garanteret.", "cta": "Book 15-minutters præstationsanalyse nu", "cta_downloads": "Download infomateriale", "stat1": {"value": "48t", "label": "Klar til brug efter bestilling"}, "stat2": {"value": "CV < 2%", "label": "Præcision over hele måleområdet"}},
        "about": {"caption": "DIN YDEEVNEGARANT", "title": "Excellence og Sikkerhed: Standarden vi sætter.", "text1": "IglooPro er en premium enhed. Men ægte premium ydeevne kommer kun fra perfekt, risikofri idriftsættelse. En standardlevering efterlader kompleksiteten til dig. Vi tager ansvaret for resultatet.", "text2": "Derfor leverer vi udelukkende løftet om 48-timers opsætning. Vores præstationssøjler garanterer, at dit POC-workflow er optimeret fra første sekund, og at du kan bruge diagnostisk excellence med det samme.", "cta": "Sikr eksklusiv fordel"},
        "doctors": {"caption": "DIAGNOSTIK FOKUS", "title": "Præcis Diagnostik. Øjeblikkelige Resultater ved Point-of-Care.", "description": "Opdag med systemer som Igloo Pro fra DX365, hvordan du kan optimere din patientpleje og levere vigtige diagnoser direkte på behandlingsstedet – med laboratoriepræcise resultater på minutter.", "cta": "Til Igloo Pro Systemet"},
        "services": {"caption": "DIAGNOSTIK FOKUS", "title": "Nøgleområder inden for forebyggende diagnostik", "poc_systemloesungen": {"title": "POC Systemløsninger", "description": "Dit kontrolcenter for diagnostik. Mobile analysatorer, der leverer laboratoriepræcise resultater på minutter direkte på behandlingsstedet (f.eks. Igloo Pro)."}, "praeventions_checks": {"title": "Forebyggende helbredstjek", "description": "Forebyggelse gentænkt. Hurtig bestemmelse af vigtige biomarkører (f.eks. D-vitamin, CRP, HbA1c) til tidlig risikodetektion og individuel sundhedsrådgivning."}, "infektion_entzuendung": {"title": "Infektions- & Inflammationsmarkører", "description": "Hurtige svar i kritiske tilfælde. Øjeblikkelig analyse af inflammationsværdier (CRP, PCT, IL-6) og infektionssygdomme – essentielt for akut pleje og triage."}, "stoffwechsel_herz": {"title": "Stofskifte & Hjertesundhed", "description": "Vigtige indikatorer på et øjeblik. Præcis måling af HbA1c, kolesterolprofiler og hjertemarkører (f.eks. D-Dimer) til overvågning af kroniske sygdomme."}, "hormon_tests": {"title": "Hormon- & Endokrinologitests", "description": "Specialdiagnostik gjort nemt. Bredt udvalg af tests for skjoldbruskkirtel- og reproduktionshormoner (TSH, AMH) til specialiserede praksisser og apoteker."}, "kompatibilitaet_integration": {"title": "Kompatibilitet på tværs af producenter", "description": "Maksimal fleksibilitet. Takket være universel teknologi evaluerer vores enheder 90% af alle laterale flow tests på markedet. Investeringssikkerhed gennem åbenhed."}},
        "testimonials": {"caption": "UDTALELSER", "title": "Hvad vores brugere siger om Igloo Pro Systemet", "ratingLabel": "Samlet vurdering\nbaseret på 3500+ anmeldelser", "positiveLabel": "Positiv vurdering", "richard_pollock": {"role": "Tandlæge (Ægte anmeldelse)", "title": "Biologisk tandlæge og implantatkirurg / Chelsea Dental Clinic", "focus": "Hurtige helbredstjek på stedet (Forebyggelse, D-vitamin)", "text": "At udføre analyse af D-vitamin niveauer og andre vigtige sundhedsindikatorer på stedet kan ikke undervurderes. Igloo Pro gør det muligt for mig at udføre en simpel kapillær blodprøve, fastslå patienternes behov og derefter vejlede dem om, hvilke yderligere kosttilskud de måtte have brug for for at optimere behandlingen. Denne evne viser sig at være transformerende med hensyn til patientresultater."}, "eva_schmidt": {"role": "Apotek", "title": "Ejer / Löwen-Apotheke, Berlin", "focus": "Næste skridt i forebyggelsesrådgivning (Kundefastholdelse, Hastighed)", "text": "Siden vi begyndte at bruge Igloo Pro Systemet, er vores rolle som sundhedsrådgivere blevet enormt styrket. Kunderne sætter stor pris på at kunne få bestemt vigtige værdier som CRP eller kolesterol på minutter i stedet for at vente ugevis på tider. En ægte win-win situation for kundefastholdelse og servicekvalitet."}, "martin_fischer": {"role": "Praktiserende læge/Praksis", "title": "Specialist i Intern Medicin / Intern Medicin Praksis Dr. Fischer", "focus": "Øjeblikkelig diagnostik for akutte patienter (Effektivitet, Terapibeslutning)", "text": "Evnen til at bestemme inflammationsmarkører som CRP øjeblikkeligt i praksissen har revolutioneret vores behandlingsworkflow. Vi kan hurtigere beslutte, om antibiotikabehandling er nødvendig for patienter med uklare infektioner og forhindre unødvendige henvisninger. Dette sparer os tid og øger patienttilfredsheden betydeligt."}, "julia_bergmann": {"role": "Klinik/Laboratorium", "title": "Leder af Laboratorium & Diagnostik / Klinikum Nord", "focus": "Systemkompatibilitet & Pålidelighed (Fleksibilitet, Samling)", "text": "Igloo Pro er den mest fleksible Point-of-Care enhed, vi nogensinde har evalueret. Kompatibiliteten på tværs af producenter for laterale flow tests er en kæmpe fordel, der giver os mulighed for at standardisere vores POC-enheder og spare omkostninger uden at skulle give afkald på den dokumenterede pålidelighed af resultaterne."}},
        "blog": {"caption": "Blog & Nyheder", "title": "Vores artikler om sundhed"}
    },
    "cs": {
        "hero": {"caption": "Výkon v místě péče", "title": "IglooPro:\nPoint-of-Care. Perfektní. Okamžité.", "description": "Zajistěte si balíček výkonu: Váš IglooPro je připraven k použití za 48 hodin – zaručeno.", "cta": "Rezervovat 15-minutovou analýzu výkonu nyní", "cta_downloads": "Stáhnout informační materiály", "stat1": {"value": "48h", "label": "Připraveno k použití po objednání"}, "stat2": {"value": "CV < 2%", "label": "Přesnost v celém měřicím rozsahu"}},
        "about": {"caption": "VÁŠ GARANT VÝKONU", "title": "Dokonalost a Bezpečnost: Standard, který nastavujeme.", "text1": "IglooPro je prémiové zařízení. Ale skutečný prémiový výkon pochází pouze z dokonalého uvedení do provozu bez rizika. Standardní dodávka nechává složitost na vás. My přebíráme odpovědnost za výsledek.", "text2": "Proto dodáváme výhradně slib nastavení do 48 hodin. Naše pilíře výkonu zaručují, že váš pracovní postup POC je optimalizován od první sekundy a že můžete okamžitě využít diagnostickou dokonalost.", "cta": "Zajistit exkluzivní výhodu"},
        "doctors": {"caption": "ZAMĚŘENÍ NA DIAGNOSTIKU", "title": "Přesná diagnostika. Okamžité výsledky v Point-of-Care.", "description": "Objevte se systémy jako Igloo Pro od DX365, jak můžete optimalizovat péči o pacienty a poskytovat důležité diagnózy přímo v místě ošetření – s laboratorně přesnými výsledky během několika minut.", "cta": "K systému Igloo Pro"},
        "services": {"caption": "ZAMĚŘENÍ NA DIAGNOSTIKU", "title": "Klíčové oblasti preventivní diagnostiky", "poc_systemloesungen": {"title": "Systémová řešení POC", "description": "Vaše řídicí centrum pro diagnostiku. Mobilní analyzátory, které poskytují laboratorně přesné výsledky během několika minut přímo v místě ošetření (např. Igloo Pro)."}, "praeventions_checks": {"title": "Preventivní zdravotní prohlídky", "description": "Prevence nově vymyšlena. Rychlé stanovení důležitých biomarkerů (např. Vitamín D, CRP, HbA1c) pro včasnou detekci rizik a individuální zdravotní poradenství."}, "infektion_entzuendung": {"title": "Markery infekce a zánětu", "description": "Rychlé odpovědi v kritických případech. Okamžitá analýza zánětlivých hodnot (CRP, PCT, IL-6) a infekčních onemocnění – nezbytné pro akutní péči a třídění."}, "stoffwechsel_herz": {"title": "Metabolismus a zdraví srdce", "description": "Důležité ukazatele na první pohled. Přesné měření HbA1c, profilů cholesterolu a srdečních markerů (např. D-Dimer) pro monitorování chronických onemocnění."}, "hormon_tests": {"title": "Hormonální a endokrinologické testy", "description": "Specializovaná diagnostika snadno. Široká škála testů hormonů štítné žlázy a reprodukčních hormonů (TSH, AMH) pro specializované praxe a lékárny."}, "kompatibilitaet_integration": {"title": "Kompatibilita mezi výrobci", "description": "Maximální flexibilita. Díky univerzální technologii naše zařízení vyhodnocují 90% všech testů s bočním tokem na trhu. Bezpečnost investice díky otevřenosti."}},
        "testimonials": {"caption": "REFERENCE", "title": "Co říkají naši uživatelé o systému Igloo Pro", "ratingLabel": "Celkové hodnocení\nna základě 3500+ recenzí", "positiveLabel": "Pozitivní hodnocení", "richard_pollock": {"role": "Zubař (Skutečná recenze)", "title": "Biologický zubař a implantolog / Chelsea Dental Clinic", "focus": "Rychlé zdravotní kontroly na místě (Prevence, Vitamín D)", "text": "Provádění analýzy hladiny vitamínu D a dalších klíčových zdravotních ukazatelů na místě nelze podceňovat. Igloo Pro mi umožňuje provést jednoduchý test kapilární krve, zjistit potřeby pacientů a poté je nasměrovat k tomu, jaké další doplňky by mohli potřebovat k optimalizaci léčby. Tato schopnost se ukazuje jako transformativní z hlediska výsledků pacientů."}, "eva_schmidt": {"role": "Lékárna", "title": "Majitelka / Löwen-Apotheke, Berlín", "focus": "Další krok v poradenství prevence (Věrnost zákazníků, Rychlost)", "text": "Od té doby, co jsme začali používat systém Igloo Pro, se naše role zdravotních poradců nesmírně posílila. Zákazníci velmi oceňují, že mohou určit důležité hodnoty jako CRP nebo cholesterol během několika minut místo čekání týdnů na termíny. Skutečná win-win situace pro věrnost zákazníků a kvalitu služeb."}, "martin_fischer": {"role": "Praktický lékař/Praxe", "title": "Specialista na vnitřní lékařství / Interní praxe Dr. Fischer", "focus": "Okamžitá diagnostika pro akutní pacienty (Efektivita, Rozhodnutí o terapii)", "text": "Schopnost okamžitě stanovit zánětlivé markery jako CRP v ordinaci způsobila revoluci v našem léčebném pracovním postupu. Můžeme se rychleji rozhodnout, zda je u pacientů s nejasnými infekcemi nutná antibiotická léčba, a zabránit zbytečným doporučením. To nám šetří čas a výrazně zvyšuje spokojenost pacientů."}, "julia_bergmann": {"role": "Klinika/Laboratoř", "title": "Vedoucí laboratoře a diagnostiky / Klinikum Nord", "focus": "Kompatibilita a spolehlivost systému (Flexibilita, Sdružování)", "text": "Igloo Pro je nejflexibilnější Point-of-Care zařízení, jaké jsme kdy hodnotili. Kompatibilita mezi výrobci pro testy s bočním tokem je obrovskou výhodou, která nám umožňuje standardizovat naše zařízení POC a šetřit náklady, aniž bychom museli rezignovat na osvědčenou spolehlivost výsledků."}},
        "blog": {"caption": "Blog a novinky", "title": "Naše články o zdraví"}
    },
    "pt": {
        "hero": {"caption": "Desempenho Point-of-Care", "title": "IglooPro:\nPoint-of-Care. Perfeito. Imediato.", "description": "Garanta o pacote de desempenho: Seu IglooPro está pronto para uso em 48 horas – garantido.", "cta": "Agendar análise de desempenho de 15 minutos agora", "cta_downloads": "Baixar materiais informativos", "stat1": {"value": "48h", "label": "Pronto para uso após o pedido"}, "stat2": {"value": "CV < 2%", "label": "Precisão em toda a faixa de medição"}},
        "about": {"caption": "SEU GARANTE DE DESEMPENHO", "title": "Excelência e Segurança: O padrão que estabelecemos.", "text1": "O IglooPro é um dispositivo premium. Mas o verdadeiro desempenho premium só vem de um comissionamento perfeito e sem riscos. Uma entrega padrão deixa a complexidade para você. Nós assumimos a responsabilidade pelo resultado.", "text2": "É por isso que entregamos exclusivamente a promessa de configuração em 48 horas. Nossos pilares de desempenho garantem que seu fluxo de trabalho POC seja otimizado desde o primeiro segundo e que você possa usar a excelência diagnóstica imediatamente.", "cta": "Garantir benefício exclusivo"},
        "doctors": {"caption": "FOCO EM DIAGNÓSTICO", "title": "Diagnóstico Preciso. Resultados Imediatos no Point-of-Care.", "description": "Descubra com sistemas como o Igloo Pro da DX365 como você pode otimizar o atendimento ao paciente e fornecer diagnósticos importantes diretamente no local do tratamento – com resultados precisos de laboratório em minutos.", "cta": "Para o Sistema Igloo Pro"},
        "services": {"caption": "FOCO EM DIAGNÓSTICO", "title": "Principais Áreas de Diagnóstico Preventivo", "poc_systemloesungen": {"title": "Soluções de Sistema POC", "description": "Seu centro de controle para diagnósticos. Analisadores móveis que fornecem resultados precisos de laboratório em minutos diretamente no local do tratamento (por exemplo, Igloo Pro)."}, "praeventions_checks": {"title": "Verificações de Saúde Preventivas", "description": "Prevenção reinventada. Determinação rápida de biomarcadores importantes (por exemplo, Vitamina D, CRP, HbA1c) para detecção precoce de riscos e aconselhamento de saúde individual."}, "infektion_entzuendung": {"title": "Marcadores de Infecção e Inflamação", "description": "Respostas rápidas em casos críticos. Análise imediata de valores de inflamação (CRP, PCT, IL-6) e doenças infecciosas – essencial para cuidados agudos e triagem."}, "stoffwechsel_herz": {"title": "Metabolismo e Saúde Cardíaca", "description": "Indicadores importantes em um relance. Medição precisa de HbA1c, perfis de colesterol e marcadores cardíacos (por exemplo, Dímero-D) para monitoramento de doenças crônicas."}, "hormon_tests": {"title": "Testes Hormonais e Endocrinologia", "description": "Diagnóstico especializado facilitado. Ampla gama de testes para hormônios tireoidianos e reprodutivos (TSH, AMH) para práticas especializadas e farmácias."}, "kompatibilitaet_integration": {"title": "Compatibilidade entre Fabricantes", "description": "Máxima flexibilidade. Graças à tecnologia universal, nossos dispositivos avaliam 90% de todos os testes de fluxo lateral do mercado. Segurança do investimento através da abertura."}},
        "testimonials": {"caption": "DEPOIMENTOS", "title": "O que nossos usuários dizem sobre o Sistema Igloo Pro", "ratingLabel": "Avaliação Geral\nbaseada em 3500+ avaliações", "positiveLabel": "Avaliação Positiva", "richard_pollock": {"role": "Dentista (Avaliação Real)", "title": "Dentista Biológico e Cirurgião de Implantes / Chelsea Dental Clinic", "focus": "Verificações rápidas de saúde no local (Prevenção, Vitamina D)", "text": "A realização de análises dos níveis de Vitamina D e outros indicadores-chave de saúde no local não pode ser subestimada. O Igloo Pro me permite realizar um teste simples de sangue capilar, verificar as necessidades dos pacientes e, em seguida, orientá-los sobre quais suplementos adicionais eles podem precisar para otimizar o tratamento. Essa capacidade está se provando transformadora em termos de resultados para os pacientes."}, "eva_schmidt": {"role": "Farmácia", "title": "Proprietária / Löwen-Apotheke, Berlim", "focus": "O próximo passo na consultoria de prevenção (Lealdade do cliente, Velocidade)", "text": "Desde que começamos a usar o Sistema Igloo Pro, nosso papel como consultores de saúde foi extremamente fortalecido. Os clientes apreciam muito poder determinar valores importantes como CRP ou colesterol em minutos, em vez de esperar semanas por consultas. Uma verdadeira situação ganha-ganha para a fidelidade do cliente e a qualidade do serviço."}, "martin_fischer": {"role": "Clínico Geral/Consultório", "title": "Especialista em Medicina Interna / Consultório de Medicina Interna Dr. Fischer", "focus": "Diagnóstico imediato para pacientes agudos (Eficiência, Decisão terapêutica)", "text": "A capacidade de determinar marcadores de inflamação como CRP imediatamente no consultório revolucionou nosso fluxo de trabalho de tratamento. Podemos decidir mais rapidamente se a terapia antibiótica é necessária para pacientes com infecções pouco claras e prevenir encaminhamentos desnecessários. Isso nos economiza tempo e aumenta significativamente a satisfação do paciente."}, "julia_bergmann": {"role": "Clínica/Laboratório", "title": "Chefe de Laboratório e Diagnóstico / Klinikum Nord", "focus": "Compatibilidade e Confiabilidade do Sistema (Flexibilidade, Agrupamento)", "text": "O Igloo Pro é o dispositivo Point-of-Care mais flexível que já avaliamos. A compatibilidade entre fabricantes para testes de fluxo lateral é uma grande vantagem que nos permite padronizar nossos dispositivos POC e economizar custos sem ter que renunciar à confiabilidade comprovada dos resultados."}},
        "blog": {"caption": "Blog e Notícias", "title": "Nossos Artigos sobre Saúde"}
    }
}

for lang in languages:
    filepath = f"public/locales/{lang}/home.json"
    content = translations.get(lang)
    if content:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(content, f, ensure_ascii=False, indent=2)
            print(f"Updated {filepath}")
    else:
        print(f"No translation for {lang}")
