/**
 * Alte Sprungmarken auf ihre feste Entsprechung.
 *
 * Bis heute entstanden die Marken aus der uebersetzten Ueberschrift plus
 * Blockindex — in DE und EN also verschieden, und bei jeder Umstellung
 * hinfaellig. Wer einen solchen Link verschickt hat, soll trotzdem am
 * richtigen Abschnitt ankommen. Diese Tabelle kann verschwinden, sobald
 * die alten Links niemanden mehr erreichen.
 */

export const LEGACY_ANCHORS: Record<string, Record<string, string>> = {
  'metabolic-health': {
    'adipositas-und-diabetes-veranlagung-13': 'marker-4',
    'all-genes-analysed-19': 'uebersicht-3',
    'all-genetic-evaluations-7': 'auswertungen',
    'alle-analysierten-gene-19': 'uebersicht-3',
    'alle-genetischen-auswertungen-7': 'auswertungen',
    'ernaehrungstyp-14': 'marker-5',
    'exercise-type-endurance-type-11': 'uebersicht-2',
    'fragen-zu-ihrem-befund-21': 'kontakt',
    'gewichtsverlust-durch-sport-12': 'marker-3',
    'how-to-read-this-report-1': 'so-lesen',
    'ihre-drei-schwerpunkte-20': 'zusammenfassung',
    'ihre-vier-beeinflussbaren-werte-3': 'ergebnis',
    'metabolic-type-balanced-type-10': 'uebersicht',
    'metabotyp-balancierter-typ-10': 'uebersicht',
    'methylation-8': 'marker',
    'methylierung-8': 'marker',
    'microrna-9': 'marker-2',
    'nutricosmetics-18': 'marker-9',
    'nutrikosmetik-18': 'marker-9',
    'nutrition-type-14': 'marker-5',
    'obesity-and-diabetes-predisposition-13': 'marker-4',
    'omega-3-and-blood-lipids-16': 'marker-7',
    'omega-3-und-blutfette-16': 'marker-7',
    'questions-about-your-report-21': 'kontakt',
    'salt-sensitivity-17': 'marker-8',
    'salzsensitivitaet-17': 'marker-8',
    'so-lesen-sie-diesen-befund-1': 'so-lesen',
    'sporttyp-ausdauertyp-11': 'uebersicht-2',
    'vitamin-uptake-15': 'marker-6',
    'vitaminaufnahme-15': 'marker-6',
    'weight-loss-through-exercise-12': 'marker-3',
    'your-four-modifiable-values-3': 'ergebnis',
    'your-three-focus-areas-20': 'zusammenfassung',
  },
  'healthy-aging': {
    'all-markers-in-overview-2': 'ergebnis',
    'alle-marker-im-ueberblick-2': 'ergebnis',
    'ernaehrung-und-lebensgewohnheiten-6': 'lebensstil',
    'fragen-zu-ihrem-befund-9': 'kontakt',
    'how-to-read-this-report-1': 'so-lesen',
    'ihre-interventionen-7': 'uebersicht',
    'ihre-zwei-schwerpunkte-8': 'zusammenfassung',
    'line-1-and-il-6-5': 'marker-2',
    'line-1-und-il-6-5': 'marker-2',
    'marker-specific-age-in-comparison-3': 'biologisches-alter',
    'markerspezifisches-alter-im-vergleich-3': 'biologisches-alter',
    'nutrition-and-lifestyle-habits-6': 'lebensstil',
    'questions-about-your-report-9': 'kontakt',
    'so-lesen-sie-diesen-befund-1': 'so-lesen',
    'telomere-und-alterungsmarker-4': 'marker',
    'telomeres-and-ageing-markers-4': 'marker',
    'your-interventions-7': 'uebersicht',
    'your-two-focus-areas-8': 'zusammenfassung',
  },
  'biologische-altersuhr': {
    'biological-age-4': 'biologisches-alter',
    'biologisches-alter-4': 'biologisches-alter',
    'der-eigentliche-befund-9': 'verlauf',
    'die-drei-micrornas-6': 'marker',
    'ernaehrung-und-lebensgewohnheiten-7': 'lebensstil',
    'fragen-zu-ihrem-befund-14': 'kontakt',
    'ihr-schwerpunkt-die-entzuendungsachse-11': 'zusammenfassung',
    'ihre-biologische-altersuhr-3': 'ergebnis',
    'ihre-interventionen-8': 'uebersicht',
    'nicht-nur-wie-alt-sie-sind-sondern-wie-schnell-s-1': 'so-lesen',
    'not-just-how-old-you-are-but-how-fast-you-are-ag-1': 'so-lesen',
    'nutrition-and-lifestyle-habits-7': 'lebensstil',
    'questions-about-your-report-14': 'kontakt',
    'scientific-context-12': 'einordnung',
    'the-actual-finding-9': 'verlauf',
    'the-three-micrornas-6': 'marker',
    'wissenschaftliche-einordnung-12': 'einordnung',
    'your-biological-age-clock-3': 'ergebnis',
    'your-focus-the-inflammation-axis-11': 'zusammenfassung',
    'your-interventions-8': 'uebersicht',
  },
  'telomer-analyse': {
    'der-eigentliche-befund-7': 'verlauf',
    'diet-and-lifestyle-habits-5': 'lebensstil',
    'ernaehrung-und-lebensgewohnheiten-5': 'lebensstil',
    'fragen-zu-ihrem-befund-12': 'kontakt',
    'ihre-interventionen-6': 'uebersicht',
    'ihre-telomere-ihre-zellulaere-reserve-1': 'so-lesen',
    'ihre-telomerlaenge-3': 'ergebnis',
    'questions-about-your-report-12': 'kontakt',
    'scientific-context-10': 'einordnung',
    'telomer-alter-4': 'biologisches-alter',
    'telomere-age-4': 'biologisches-alter',
    'the-actual-finding-7': 'verlauf',
    'two-levers-and-one-is-the-bigger-one-9': 'zusammenfassung',
    'wissenschaftliche-einordnung-10': 'einordnung',
    'your-interventions-6': 'uebersicht',
    'your-telomere-length-3': 'ergebnis',
    'your-telomeres-your-cellular-reserve-1': 'so-lesen',
    'zwei-hebel-und-einer-ist-der-groessere-9': 'zusammenfassung',
  },
  'stress-monitor': {
    'all-micrornas-at-a-glance-4': 'ergebnis',
    'alle-micrornas-im-ueberblick-4': 'ergebnis',
    'compounds-for-evaluation-01-8': 'uebersicht',
    'compounds-for-evaluation-02-11': 'uebersicht-2',
    'die-beiden-einzelindikatoren-6': 'marker-2',
    'die-vier-micrornas-10': 'marker-3',
    'fragen-zu-ihrem-befund-16': 'kontakt',
    'ihr-schwerpunkt-die-lange-linie-15': 'zusammenfassung',
    'ihre-interventionen-12': 'uebersicht-3',
    'ihre-stress-regulation-nicht-ihr-stresslevel-1': 'so-lesen',
    'ihre-zwei-auswertungen-3': 'marker',
    'physiological-stress-level-5': 'ergebnis-2',
    'physiologisches-stresslevel-5': 'ergebnis-2',
    'questions-about-your-report-16': 'kontakt',
    'risiko-fuer-spaetfolgen-9': 'ergebnis-3',
    'risk-of-long-term-effects-9': 'ergebnis-3',
    'the-four-micrornas-10': 'marker-3',
    'the-two-individual-indicators-6': 'marker-2',
    'two-measurements-compared-13': 'verlauf',
    'wirkstoffe-zu-auswertung-01-8': 'uebersicht',
    'wirkstoffe-zu-auswertung-02-11': 'uebersicht-2',
    'your-focus-the-long-view-15': 'zusammenfassung',
    'your-interventions-12': 'uebersicht-3',
    'your-stress-regulation-not-your-stress-level-1': 'so-lesen',
    'your-two-evaluations-3': 'marker',
    'zwei-messungen-im-vergleich-13': 'verlauf',
  },
  'healthy-sport': {
    'die-acht-micrornas-5': 'uebersicht',
    'drei-weitere-genetische-auswertungen-11': 'uebersicht-3',
    'ernaehrung-und-lebensgewohnheiten-12': 'lebensstil',
    'fragen-zu-ihrem-befund-17': 'kontakt',
    'how-to-read-this-report-1': 'so-lesen',
    'ihr-schwerpunkt-erholung-16': 'zusammenfassung',
    'ihre-interventionen-13': 'uebersicht-4',
    'ihre-sieben-auswertungen-3': 'auswertungen',
    'ihre-sportmarker-10': 'uebersicht-2',
    'leistung-und-erholung-9': 'marker-2',
    'nutrition-and-lifestyle-habits-12': 'lebensstil',
    'performance-and-recovery-9': 'marker-2',
    'questions-about-your-report-17': 'kontakt',
    'so-lesen-sie-diesen-befund-1': 'so-lesen',
    'the-eight-micrornas-5': 'uebersicht',
    'three-further-genetic-assessments-11': 'uebersicht-3',
    'two-measurements-compared-14': 'verlauf',
    'was-vorrang-hat-7': 'marker',
    'what-takes-priority-7': 'marker',
    'your-focus-recovery-16': 'zusammenfassung',
    'your-interventions-13': 'uebersicht-4',
    'your-seven-assessments-3': 'auswertungen',
    'your-sport-markers-10': 'uebersicht-2',
    'zwei-messungen-im-vergleich-14': 'verlauf',
  },
}
